name: cyberflix_web
description: "Cyberflix Catalog"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  reorderables: ^0.6.0
  http_requests: ^3.1.0
  url_launcher: ^6.2.4
  flutter_widget_from_html: ^0.14.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg_image.jpeg
    - assets/logo.png
    - assets/github.png
    - assets/kofi.png
    - assets/thumbsup.png
